### ISSUE TITLE
Font in the event block is a little bit too large 

### ISSUE THREAD

**Issue by neverov** [notwaldorf/picasso#10]
Hey Monica, thanks for the extension, it's great! 

I'm giving it a try and so far it's awesome.
I have a question/request about the font size:
Here's how it looked like before: 
![trucker path - calendar - week of mar 27 2017 2017-03-29 12-20-13](https://cloud.githubusercontent.com/assets/57802/24447668/6d925f92-147a-11e7-854e-7cb481bbcb77.png)
And here's how it looks like with the extension enabled:
![trucker path - calendar - week of mar 27 2017 2017-03-29 12-20-41](https://cloud.githubusercontent.com/assets/57802/24447702/84e2b19c-147a-11e7-9469-3a832c5317ae.png)

Notice, how's the last line goes "under" the block. Most of the time I use 1-hour blocks and it's very convenient to have a meeting room or an address visible at a glance. 

Do you think it's a good idea to adjust the font size to make it happen or maybe make it adjustable or something else?

**Comment by neverov** [comment]
Bump.

**Comment by notwaldorf** [comment]
Closing -- this extension is deprecated (and most importantly: no longer works with the new Calendar UI update)
