### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by patrick91** [notwaldorf/picasso#5]
Works on Opera too! I tried using the [Download chrome extensions](https://addons.opera.com/en-gb/extensions/details/download-chrome-extension-9/) addon.

Maybe it is worth adding to the readme? Or submitting it to the [Opera Store](https://addons.opera.com/en/)

**Comment by notwaldorf** [comment]
@patrick91 Adding it to the readme would be awesome! I am starting to get web store fatigue, so I don't really want to make a third store account :)
